apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../../external-service/base"
namePrefix: argo-

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: external-host
    envs:
      - "params.env"
replacements:
  - path: "replacements.yaml"
