---
# Source: gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-egressgateway
  namespace: istio-egress
  labels:
    helm.sh/chart: gateway-1.15.2
    app: istio-egressgateway
    istio: egressgateway
    app.kubernetes.io/version: "1.15.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-egressgateway
