apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-crt
spec:
  secretName: letsencrypt-crt-secret
  dnsNames:
    - pbl6.mamlong34.monster
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
