apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-ingress
resources:
  - namespace.yaml
  - helm-template.yaml
  - gateway.yaml
  - tls-redirect-virtual-service.yaml
  - prod-issuer.yaml
  - staging-issuer.yaml
  - certificate.yaml
patchesStrategicMerge:
  - "patches/budget-LB.yaml"
