apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
spec:
  template:
    spec:
      nodeSelector:
        dedicated: ingress
      tolerations:
        - key: dedicated
          operator: "Equal"
          value: ingress
          effect: "NoSchedule"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      nodeSelector:
        dedicated: ingress
      tolerations:
        - key: dedicated
          operator: "Equal"
          value: ingress
          effect: "NoSchedule"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      nodeSelector:
        dedicated: ingress
      tolerations:
        - key: dedicated
          operator: "Equal"
          value: ingress
          effect: "NoSchedule"
