apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - mysql-secret.yaml
  - namespace.yaml
  - service-account.yaml
  - service.yaml
  - virtual-service.yaml
namespace: songs-uploader
commonLabels:
  app.kubernetes.io/name: songs-uploader
  app.kubernetes.io/version: 0.0.1
