apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "crds/crds.yaml"
  - "templates/clusterrole.yaml"
  - "templates/clusterrolebinding.yaml"
  - "templates/deployment.yaml"
  - "templates/serviceaccount.yaml"
  - "namespace.yaml"
patchesJson6902:
  - path: "patches/allow-custom-image.yaml"
    target:
      kind: Deployment
      name: kiali-operator
      namespace: kiali-operator
      group: apps
      version: v1
