apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - virtual-service.yaml
namespace: web
commonLabels:
  app.kubernetes.io/name: web
  app.kubernetes.io/version: 0.0.1
