apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: preprocess
  namespace: ml
spec:
  entrypoint: preprocess-data
  serviceAccountName: executor
  templates:
    - name: preprocess-data
      metadata:
        annotations:
          proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      inputs:
        artifacts:
          - name: dataset
            path: /dataset.zip
            gcs:
              bucket: pbl6-363916-europe-central2-dataset-859a
              key: neural-audio-fingerprint.zip
      outputs:
        artifacts:
          - name: processed-dataset
            path: /processed-dataset
            s3:
              endpoint: minio.minio.svc.cluster.local:9000
              insecure: true
              bucket: dataset
              key: neural-audio-fp-dataset
              accessKeySecret:
                name: minio-artifact
                key: accesskey
              secretKeySecret:
                name: minio-artifact
                key: secretkey
      container:
        image: europe-docker.pkg.dev/pbl6-363916/mirror/preprocessing
        imagePullPolicy: Always
        command: ["data-processing"]
        args:
          [
            "--zip-path",
            "/dataset.zip",
            "--source-root-dir",
            "neural-audio-fp-dataset/music/",
            "--bg-root-dir",
            "neural-audio-fp-dataset/aug/bg/",
            "--ir-root-dir",
            "neural-audio-fp-dataset/aug/ir/",
            "--output-dir",
            "/processed-dataset",
            "--duration",
            "1.0",
            "--hop",
            "0.5",
            "--fs",
            "8000",
            "--train-snr-min",
            "0",
            "--train-snr-max",
            "10",
            "--val-snr-min",
            "0",
            "--val-snr-max",
            "10",
            "--test-snr-min",
            "0",
            "--test-snr-max",
            "10",
            "--train-use-bg-aug",
            "--train-use-ir-aug",
            "--val-use-bg-aug",
            "--val-use-ir-aug",
            "--test-use-bg-aug",
            "--test-use-ir-aug",
          ]
