apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: train-index
  namespace: ml
spec:
  entrypoint: train-index
  serviceAccountName: executor
  templates:
    - name: train-index
      metadata:
        annotations:
          proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      inputs:
        artifacts:
          - name: embeds
            path: /embeds
            s3:
              endpoint: minio.minio.svc.cluster.local:9000
              insecure: true
              bucket: datasets
              key: embeds
              accessKeySecret:
                name: minio-artifact
                key: accesskey
              secretKeySecret:
                name: minio-artifact
                key: secretkey
      container:
        image: europe-docker.pkg.dev/pbl6-363916/mirror/indexer
        imagePullPolicy: Always
        command: ["/opt/conda/bin/conda", "run"]
        args:
          - "python3"
          - "-m"
          - "app.cli"
        env:
          - name: INDEX_PATH
            value: /faiss.index
          - name: EMB_DIR
            value: /embeds/
      outputs:
        artifacts:
          - name: faiss-index
            path: /faiss.index
            s3:
              endpoint: minio.minio.svc.cluster.local:9000
              insecure: true
              bucket: datasets
              key: faiss.index
              accessKeySecret:
                name: minio-artifact
                key: accesskey
              secretKeySecret:
                name: minio-artifact
                key: secretkey
