apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: train-mnist
  namespace: ml
spec:
  entrypoint: ml-pipeline
  serviceAccountName: executor
  templates:
    - name: ml-pipeline
      steps:
        - - name: process-data
            template: process-data
        - - name: train-model
            template: train-model
    - name: process-data
      metadata:
        annotations:
          proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      inputs:
        artifacts:
          - name: datasets
            path: /datasets
            s3:
              endpoint: minio.minio.svc.cluster.local:9000
              insecure: true
              bucket: datasets
              key: mnist
              accessKeySecret:
                name: minio-artifact
                key: accesskey
              secretKeySecret:
                name: minio-artifact
                key: secretkey
      outputs:
        artifacts:
          - name: processed-datasets
            path: /processed-datasets/mnist.npz
            s3:
              endpoint: minio.minio.svc.cluster.local:9000
              insecure: true
              bucket: datasets
              key: mnist/processed/mnist.npz
              accessKeySecret:
                name: minio-artifact
                key: accesskey
              secretKeySecret:
                name: minio-artifact
                key: secretkey
      container:
        image: europe-docker.pkg.dev/pbl6-363916/mirror/mnist-data-processing
        imagePullPolicy: Always
        command: [python]
        args:
          [
            "processing.py",
            "--input_dir",
            "/datasets",
            "--output_dir",
            "/processed-datasets",
          ]
    - name: train-model
      metadata:
        annotations:
          proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      inputs:
        artifacts:
          - name: processed-datasets
            path: /processed-datasets/mnist.npz
            s3:
              endpoint: minio.minio.svc.cluster.local:9000
              insecure: true
              bucket: datasets
              key: mnist/processed/mnist.npz
              accessKeySecret:
                name: minio-artifact
                key: accesskey
              secretKeySecret:
                name: minio-artifact
                key: secretkey
      container:
        image: europe-docker.pkg.dev/pbl6-363916/mirror/mnist-model-training
        imagePullPolicy: Always
        command: [python]
        args:
          [
            "reinforce.py",
            "--dataset_dir",
            "/processed-datasets",
            "--tracking_uri",
            "http://mlflow.mlflow.svc.cluster.local",
            "--epochs",
            "20",
            "--batch_size",
            "128",
            "--verbose",
            "1",
            "--validation_split",
            "0.2",
            "--shuffle",
            "True",
          ]
