---
# Source: mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: "mariadb"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-11.3.3
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "cm9vdA=="
