---
# Source: minio/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: "minio"
  labels:
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-11.10.9
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
secrets:
  - name: minio
