---
# Source: kiali-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali-operator
  labels:
    helm.sh/chart: kiali-operator-1.54.0
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    version: "v1.54.0"
    app.kubernetes.io/version: "v1.54.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali-operator"
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - pods
      - serviceaccounts
      - services
      - services/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - get
      - list
      - patch
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - create
      - list
      - watch
  - apiGroups: [""]
    resourceNames:
      - cacerts
      - istio-ca-secret
    resources:
      - secrets
    verbs:
      - get
  - apiGroups: [""]
    resourceNames:
      - kiali-signing-key
    resources:
      - secrets
    verbs:
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
    verbs:
      - create
      - get
  - apiGroups: ["apps"]
    resourceNames:
      - kiali-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups: ["kiali.io"]
    resources:
      - "*"
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - selfsubjectaccessreviews
    verbs:
      - list
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["route.openshift.io"]
    resources:
      - routes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["oauth.openshift.io"]
    resources:
      - oauthclients
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["config.openshift.io"]
    resources:
      - clusteroperators
    verbs:
      - list
      - watch
  - apiGroups: ["config.openshift.io"]
    resourceNames:
      - kube-apiserver
    resources:
      - clusteroperators
    verbs:
      - get
  - apiGroups: ["console.openshift.io"]
    resources:
      - consolelinks
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # The permissions below are for Kiali itself; operator needs these so it can escalate when creating Kiali's roles
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups: [""]
    resources:
      - pods/portforward
    verbs:
      - create
      - post
  - apiGroups: ["extensions", "apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - config.istio.io
      - networking.istio.io
      - authentication.istio.io
      - rbac.istio.io
      - security.istio.io
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups: ["apps.openshift.io"]
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups: ["project.openshift.io"]
    resources:
      - projects
    verbs:
      - get
  - apiGroups: ["route.openshift.io"]
    resources:
      - routes
    verbs:
      - get
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs:
      - create
