apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/manifests/argocd
    repoURL: https://github.com/vohoanglong0107/PBL6
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      # remove the this after a traumatizing experience of
      # not being able to remove or update argocd itself
      # by kubectl
      # selfHeal: true
