apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.14/manifests/install.yaml
  - namespace.yaml
  - virtual-service.yaml
patchesStrategicMerge:
  - patches/insecure-mode.yaml
  - patches/reduce-resource-requested.yaml
images:
  - name: quay.io/argoproj/argocd
    newName: europe-docker.pkg.dev/pbl6-363916/mirror/argocd
    newTag: v2.4.14
  - name: ghcr.io/dexidp/dex
    newName: europe-docker.pkg.dev/pbl6-363916/mirror/dex
    newTag: v2.35.1-distroless
