apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: indexer
  namespace: argocd
spec:
  destination:
    namespace: indexer
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/manifests/apps/indexer
    repoURL: https://github.com/vohoanglong0107/PBL6
    targetRevision: main
