apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
namespace: indexer
commonLabels:
  app.kubernetes.io/name: indexer
  app.kubernetes.io/version: 0.0.1
