apiVersion: v1
kind: Service
metadata:
  name: indexer
  labels:
    app: indexer
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: indexer
