"""empty message

Revision ID: dfede456d2c9
Revises: 
Create Date: 2022-12-01 23:20:19.734026

"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = "dfede456d2c9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "song",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", mysql.TEXT(), nullable=True),
        sa.Column("artist", mysql.TEXT(), nullable=True),
        sa.Column("url", mysql.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("song")
    # ### end Alembic commands ###
