apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "https://github.com/kubeflow/manifests/apps/volumes-web-app/upstream/overlays/istio?ref=v1.6.0"
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: deployment
    path: patches/disable-https.yaml 
