apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  namespace: istio-system
  name: kiali
  labels:
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    version: "v1.54.0"
    app.kubernetes.io/version: "v1.54.0"
  annotations:
    ansible.sdk.operatorframework.io/verbosity: "1"
spec:
  deployment:
    accessible_namespaces:
      - "**"
    image_name: europe-docker.pkg.dev/pbl6-363916/mirror/kiali
    image_version: v1.54.0
