apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../external-service/overlays/tls"
namePrefix: lets-encrypt-staging-

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: external-host
    envs:
      - "params.env"
replacements:
  - path: "replacements.yaml"
