apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - mysql-secret.yaml
  - minio-secret.yaml
  - namespace.yaml
  - service.yaml
  - virtual-service.yaml
namespace: mlflow
commonLabels:
  app.kubernetes.io/name: mlflow
  app.kubernetes.io/version: 0.0.1
