apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mlflow
spec:
  gateways:
    - istio-ingress/cluster-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /mlflow/
      rewrite:
        uri: /
      route:
        - destination:
            host: mlflow
            port:
              number: 80
