apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mlflow
spec:
  gateways:
    - istio-ingress/cluster-gateway
  hosts:
    - "mlflow.pbl6.mamlong34.monster"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: mlflow
            port:
              number: 80
