auth:
  rootUser: minio
  rootPassword: minio123
image:
  registry: europe-docker.pkg.dev/pbl6-363916/mirror
  repository: minio
  tag: 2022.10.20-debian-11-r0
resources:
  requests:
    memory: 32Mi
    cpu: 10m
  limits:
    memory: 512Mi
    cpu: 250m
