apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v3.4.2/install.yaml
  - namespace.yaml
  - minio-artifact-secret.yaml
  - virtual-service.yaml
images:
  - name: quay.io/argoproj/argocli:v3.4.2
    newName: europe-docker.pkg.dev/pbl6-363916/mirror/argocli
    newTag: v3.4.2
  - name: quay.io/argoproj/workflow-controller:v3.4.2
    newName: europe-docker.pkg.dev/pbl6-363916/mirror/workflow-controller
    newTag: v3.4.2
patchesStrategicMerge:
  - patches/minio-artifact-repository.yaml
  - patches/insecure-mode.yaml
  - patches/disable-auth.yaml
  - patches/change-default-executor.yaml
