apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - mysql-secret.yaml
  - namespace.yaml
  - service.yaml
namespace: fingerprinter
commonLabels:
  app.kubernetes.io/name: fingerprinter
  app.kubernetes.io/version: 0.0.1
